name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Создаем директорию если не существует
          mkdir -p /var/www/demo2-corporate-services-website
          cd /var/www/demo2-corporate-services-website
          
          # Клонируем или обновляем репозиторий
          if [ ! -d ".git" ]; then
            git clone https://github.com/tagsmith-org/demo2-corporate-services-website.git .
          else
            git pull origin main
          fi
          
          # Устанавливаем Node.js если не установлен
          if ! command -v node &> /dev/null; then
            curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
            apt-get install -y nodejs
          fi
          
          # Устанавливаем зависимости и собираем
          npm ci
          npm run build
          
          # Копируем файлы из dist в корень
          cp -r dist/* .
          rm -rf dist
          
          # Проверяем что файлы скопировались
          ls -la
          
          # Устанавливаем правильные права
          chown -R www-data:www-data /var/www/demo2-corporate-services-website
          chmod -R 755 /var/www/demo2-corporate-services-website
          
          # Настраиваем nginx если не настроен
          if [ ! -f "/etc/nginx/sites-enabled/demo2.websmith-shop.com" ]; then
            cat > /etc/nginx/sites-available/demo2.websmith-shop.com << 'NGINX_EOF'
          server {
              listen 80;
              server_name demo2.websmith-shop.com;
              
              root /var/www/demo2-corporate-services-website;
              index index.html;
              
              location / {
                  try_files $uri $uri/ /index.html;
              }
              
              location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
                  expires 1y;
                  add_header Cache-Control "public, immutable";
              }
          }
          NGINX_EOF
          
          ln -sf /etc/nginx/sites-available/demo2.websmith-shop.com /etc/nginx/sites-enabled/
          fi
          
          # Перезагружаем nginx
          nginx -t && systemctl reload nginx
